// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountFormRequirement } from "./AccountFormRequirement";

/**
 * One button the connect form should offer, everything already in the reader's
 * language.
 */
export type AccountFormAction = { key: string, label: string, busy_label: string | null, success: string | null, hint: string | null, requires: Array<AccountFormRequirement>, };
