// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a synthesised birthday calendar is a layer OF, carried on its
 * [`crate::wire::CalendarRow`] so a frontend names it in its own language
 * ("Geburtstage – Familie") instead of the core stamping English text into the
 * name for the frontend to cut off again (DESIGN §4.5 a).
 */
export type BirthdayLayer = { 
/**
 * The contact list whose birthdays the calendar shows.
 */
contact_list_id: string, 
/**
 * That list's name, as its source calls it.
 */
list_name: string, };
