// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BirthdayLayer } from "./BirthdayLayer";
import type { ColorLabelId } from "./ColorLabelId";
import type { ContainerColor } from "./ContainerColor";
import type { RecurrenceCapabilities } from "./RecurrenceCapabilities";
import type { SoundConfig } from "./SoundConfig";

/**
 * A calendar plus the account that owns it and the recurrence shapes that
 * account's adapter can store.
 *
 * The event editor greys out options the source cannot round-trip — EWS has no
 * yearly interval, for instance. The local store and any account whose plugin
 * cannot be resolved report [`RecurrenceCapabilities::default`], i.e. full
 * RFC 5545: a missing manifest must not silently strip options the source may
 * well support.
 */
export type CalendarRow = { account_id: string, recurrence_capabilities: RecurrenceCapabilities, 
/**
 * Set on a synthesised birthday calendar (DESIGN §10.3), and only there:
 * which contact list it shows. The row's `name` is then that list's own
 * name, and a frontend builds what it shows — "Geburtstage – Familie" —
 * from this and its own catalog. Stamped by [`CalendarRow::new`] from the
 * calendar id, so no host can forget it.
 */
birthdays?: BirthdayLayer, id: string, name: string, color: ContainerColor | null, 
/**
 * Optional binding to a global color label. When set, the rendered
 * color resolves to the label's *current* hex (so recoloring the
 * label recolors the container), taking priority over `color`. The
 * id refers to a `ColorLabel`. `#[serde(default)]` keeps older wire
 * payloads (no binding) deserialising.
 */
color_label: ColorLabelId | null, 
/**
 * Read-only calendars (e.g. birthdays, public holidays, subscribed iCal
 * feeds) cannot be modified by the caller.
 */
read_only: boolean, 
/**
 * Default sound for reminders of all events in this calendar.
 */
default_sound: SoundConfig | null, 
/**
 * True when the backing provider can email attendees about
 * invitations / updates / cancellations via *server-side* scheduling
 * (no client SMTP): EWS, Google and Microsoft Graph always; CalDAV
 * only when the server advertises RFC 6638 auto-scheduling; local /
 * iCal never. Gates the "notify attendees" toggle in the UI.
 * `#[serde(default)]` keeps older wire payloads + stores (which never
 * set it) deserialising as `false`.
 */
supports_scheduling: boolean, 
/**
 * True when the backing provider can store a per-event color
 * *natively* (RFC 7986 `COLOR`) so the color syncs to other clients
 * and round-trips: **local** always; **CalDAV** when the server is
 * color-capable (set to `!iCloud` by the CalDAV adapter); **Google /
 * Microsoft Graph / EWS / iCal** never. When `false`, the host keeps a
 * per-event color as a host-local override instead (the Stage 1
 * `event_color_overrides` table). Gates how the frontend routes a
 * recolor — through `update_event` (native) vs `set_event_color`
 * (override). `#[serde(default)]` keeps older wire payloads + stores
 * (which never set it) deserialising as `false`.
 */
supports_event_color: boolean, 
/**
 * True when the provider itself mails the invitees about every saved
 * change to a meeting the account organizes, and about its deletion, so
 * neither can be silent (decisions 76a, 80a). The editors then say so
 * instead of offering "Notify attendees" or "Remove without notifying".
 * CalDAV sets it on an RFC 6638 server (implicit scheduling: the
 * organizer's copy is the invitation); Microsoft Graph on its calendars
 * (decision 82b). `#[serde(default)]` keeps older payloads and stores
 * deserialising as `false`.
 */
always_notifies_attendees: boolean, 
/**
 * True when, on a meeting someone else organizes, the provider accepts
 * only the attendee's own changes (RFC 6638 §3.2.2.1, implicit
 * scheduling): the reply, the attendee's own alarms, skipping an
 * occurrence, removing the copy. Everything else it refuses with a 403
 * `allowed-attendee-scheduling-object-change`. The editors then show
 * such a meeting read-only apart from those (decision 77a) and a delete
 * says the organizer gets a decline (83b). CalDAV sets it on a
 * scheduling server; every other adapter leaves it false — Microsoft
 * Graph mails the guests by itself (82b) but takes an invitee's edits,
 * so [`Calendar::always_notifies_attendees`] cannot double as this flag.
 * `#[serde(default)]` keeps older payloads and stored listings
 * deserialising as `false`.
 */
invitations_reply_only: boolean, 
/**
 * The service the editors name when they say so ("iCloud informs the
 * attendees …"), as the adapter knows it; `None` reads as "the calendar
 * server". A display string only: no rule looks at it.
 */
notifier_name?: string, };
