// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a field is presented and validated. Drives the input type on both
 * frontends — including the on-screen keyboard on mobile, which is why `Url`
 * is worth distinguishing from `Text`.
 */
export type AccountFieldKind = "text" | "url" | "secret" | "bool" | "number" | "choice" | "directory" | "file";
