// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(cal_ffiFFI)
import cal_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cal_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cal_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCalFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * A yearless calendar anchor, e.g. `{ month: 4, day: 1 }` for "April 1".
 * Mirrors [`cal_core::MonthDay`].
 */
public struct MonthDay: Equatable, Hashable {
    public var month: UInt8
    public var day: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(month: UInt8, day: UInt8) {
        self.month = month
        self.day = day
    }

    

    
}

#if compiler(>=6)
extension MonthDay: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMonthDay: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MonthDay {
        return
            try MonthDay(
                month: FfiConverterUInt8.read(from: &buf), 
                day: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: MonthDay, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.month, into: &buf)
        FfiConverterUInt8.write(value.day, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMonthDay_lift(_ buf: RustBuffer) throws -> MonthDay {
    return try FfiConverterTypeMonthDay.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMonthDay_lower(_ value: MonthDay) -> RustBuffer {
    return FfiConverterTypeMonthDay.lower(value)
}


/**
 * A parsed attendee entry: an optional display name plus the email address.
 *
 * Mirrors the `(Option<String>, String)` tuple [`cal_core::attendee::parse`]
 * returns — UniFFI needs a named record rather than a bare tuple.
 */
public struct ParsedAttendee: Equatable, Hashable {
    /**
     * Display name, if the entry carried one (`"Jane Doe <jane@host>"`).
     */
    public var name: String?
    /**
     * The email address (authoritative; taken verbatim from the entry).
     */
    public var email: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Display name, if the entry carried one (`"Jane Doe <jane@host>"`).
         */name: String?, 
        /**
         * The email address (authoritative; taken verbatim from the entry).
         */email: String) {
        self.name = name
        self.email = email
    }

    

    
}

#if compiler(>=6)
extension ParsedAttendee: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParsedAttendee: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParsedAttendee {
        return
            try ParsedAttendee(
                name: FfiConverterOptionString.read(from: &buf), 
                email: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ParsedAttendee, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedAttendee_lift(_ buf: RustBuffer) throws -> ParsedAttendee {
    return try FfiConverterTypeParsedAttendee.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedAttendee_lower(_ value: ParsedAttendee) -> RustBuffer {
    return FfiConverterTypeParsedAttendee.lower(value)
}


/**
 * Structured task recurrence. Mirrors [`cal_core::TaskRecurrence`] (with the
 * `UNTIL` date represented as a string — see [`RecurrenceEnd`]).
 */
public struct TaskRecurrence: Equatable, Hashable {
    public var frequency: RecurrenceFrequency
    public var interval: UInt32
    public var dayOfWeek: [Weekday]?
    public var dayOfMonth: UInt8?
    public var end: RecurrenceEnd?
    public var anchor: RecurrenceAnchor
    public var placement: RecurrencePlacement
    public var fixedDates: [MonthDay]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(frequency: RecurrenceFrequency, interval: UInt32, dayOfWeek: [Weekday]?, dayOfMonth: UInt8?, end: RecurrenceEnd?, anchor: RecurrenceAnchor, placement: RecurrencePlacement, fixedDates: [MonthDay]?) {
        self.frequency = frequency
        self.interval = interval
        self.dayOfWeek = dayOfWeek
        self.dayOfMonth = dayOfMonth
        self.end = end
        self.anchor = anchor
        self.placement = placement
        self.fixedDates = fixedDates
    }

    

    
}

#if compiler(>=6)
extension TaskRecurrence: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskRecurrence: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskRecurrence {
        return
            try TaskRecurrence(
                frequency: FfiConverterTypeRecurrenceFrequency.read(from: &buf), 
                interval: FfiConverterUInt32.read(from: &buf), 
                dayOfWeek: FfiConverterOptionSequenceTypeWeekday.read(from: &buf), 
                dayOfMonth: FfiConverterOptionUInt8.read(from: &buf), 
                end: FfiConverterOptionTypeRecurrenceEnd.read(from: &buf), 
                anchor: FfiConverterTypeRecurrenceAnchor.read(from: &buf), 
                placement: FfiConverterTypeRecurrencePlacement.read(from: &buf), 
                fixedDates: FfiConverterOptionSequenceTypeMonthDay.read(from: &buf)
        )
    }

    public static func write(_ value: TaskRecurrence, into buf: inout [UInt8]) {
        FfiConverterTypeRecurrenceFrequency.write(value.frequency, into: &buf)
        FfiConverterUInt32.write(value.interval, into: &buf)
        FfiConverterOptionSequenceTypeWeekday.write(value.dayOfWeek, into: &buf)
        FfiConverterOptionUInt8.write(value.dayOfMonth, into: &buf)
        FfiConverterOptionTypeRecurrenceEnd.write(value.end, into: &buf)
        FfiConverterTypeRecurrenceAnchor.write(value.anchor, into: &buf)
        FfiConverterTypeRecurrencePlacement.write(value.placement, into: &buf)
        FfiConverterOptionSequenceTypeMonthDay.write(value.fixedDates, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskRecurrence_lift(_ buf: RustBuffer) throws -> TaskRecurrence {
    return try FfiConverterTypeTaskRecurrence.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskRecurrence_lower(_ value: TaskRecurrence) -> RustBuffer {
    return FfiConverterTypeTaskRecurrence.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * From when the next instance is computed (DESIGN §9.12).
 * Mirrors [`cal_core::RecurrenceAnchor`].
 */

public enum RecurrenceAnchor: Equatable, Hashable {
    
    /**
     * Advance from the task's own date.
     */
    case fromDate
    /**
     * Advance from when the task was completed.
     */
    case fromCompletion





}

#if compiler(>=6)
extension RecurrenceAnchor: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecurrenceAnchor: FfiConverterRustBuffer {
    typealias SwiftType = RecurrenceAnchor

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecurrenceAnchor {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .fromDate
        
        case 2: return .fromCompletion
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RecurrenceAnchor, into buf: inout [UInt8]) {
        switch value {
        
        
        case .fromDate:
            writeInt(&buf, Int32(1))
        
        
        case .fromCompletion:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceAnchor_lift(_ buf: RustBuffer) throws -> RecurrenceAnchor {
    return try FfiConverterTypeRecurrenceAnchor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceAnchor_lower(_ value: RecurrenceAnchor) -> RustBuffer {
    return FfiConverterTypeRecurrenceAnchor.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * When a recurrence stops. Mirrors [`cal_core::RecurrenceEnd`], except the
 * `OnDate` date is an ISO `YYYY-MM-DD` string on the FFI boundary (UniFFI has
 * no built-in date type); it is parsed back to a real date when converted into
 * the core model.
 */

public enum RecurrenceEnd: Equatable, Hashable {
    
    /**
     * Repeats forever.
     */
    case never
    /**
     * Stops after a fixed number of occurrences (`COUNT`).
     */
    case after(occurrences: UInt32
    )
    /**
     * Stops on a date (`UNTIL`), as `YYYY-MM-DD`.
     */
    case onDate(date: String
    )





}

#if compiler(>=6)
extension RecurrenceEnd: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecurrenceEnd: FfiConverterRustBuffer {
    typealias SwiftType = RecurrenceEnd

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecurrenceEnd {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .never
        
        case 2: return .after(occurrences: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 3: return .onDate(date: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RecurrenceEnd, into buf: inout [UInt8]) {
        switch value {
        
        
        case .never:
            writeInt(&buf, Int32(1))
        
        
        case let .after(occurrences):
            writeInt(&buf, Int32(2))
            FfiConverterUInt32.write(occurrences, into: &buf)
            
        
        case let .onDate(date):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(date, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceEnd_lift(_ buf: RustBuffer) throws -> RecurrenceEnd {
    return try FfiConverterTypeRecurrenceEnd.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceEnd_lower(_ value: RecurrenceEnd) -> RustBuffer {
    return FfiConverterTypeRecurrenceEnd.lower(value)
}



/**
 * Error returned when a [`TaskRecurrence`] coming from the foreign side cannot
 * be turned into the core model.
 */
public enum RecurrenceError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The `OnDate` end carried a string that is not a valid `YYYY-MM-DD` date.
     */
    case InvalidDate(date: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension RecurrenceError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecurrenceError: FfiConverterRustBuffer {
    typealias SwiftType = RecurrenceError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecurrenceError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidDate(
            date: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RecurrenceError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidDate(date):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(date, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceError_lift(_ buf: RustBuffer) throws -> RecurrenceError {
    return try FfiConverterTypeRecurrenceError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceError_lower(_ value: RecurrenceError) -> RustBuffer {
    return FfiConverterTypeRecurrenceError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * How often a recurring task repeats. Mirrors [`cal_core::RecurrenceFrequency`].
 */

public enum RecurrenceFrequency: Equatable, Hashable {
    
    case daily
    case weekly
    case monthly
    case yearly





}

#if compiler(>=6)
extension RecurrenceFrequency: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecurrenceFrequency: FfiConverterRustBuffer {
    typealias SwiftType = RecurrenceFrequency

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecurrenceFrequency {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .daily
        
        case 2: return .weekly
        
        case 3: return .monthly
        
        case 4: return .yearly
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RecurrenceFrequency, into buf: inout [UInt8]) {
        switch value {
        
        
        case .daily:
            writeInt(&buf, Int32(1))
        
        
        case .weekly:
            writeInt(&buf, Int32(2))
        
        
        case .monthly:
            writeInt(&buf, Int32(3))
        
        
        case .yearly:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceFrequency_lift(_ buf: RustBuffer) throws -> RecurrenceFrequency {
    return try FfiConverterTypeRecurrenceFrequency.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrenceFrequency_lower(_ value: RecurrenceFrequency) -> RustBuffer {
    return FfiConverterTypeRecurrenceFrequency.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Where a recurring task's next instance is placed (DESIGN §9.12).
 * Mirrors [`cal_core::RecurrencePlacement`].
 */

public enum RecurrencePlacement: Equatable, Hashable {
    
    /**
     * The next instance gets the computed date.
     */
    case schedule
    /**
     * The next instance is undated and surfaces in the backlog.
     */
    case backlog





}

#if compiler(>=6)
extension RecurrencePlacement: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecurrencePlacement: FfiConverterRustBuffer {
    typealias SwiftType = RecurrencePlacement

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecurrencePlacement {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .schedule
        
        case 2: return .backlog
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RecurrencePlacement, into buf: inout [UInt8]) {
        switch value {
        
        
        case .schedule:
            writeInt(&buf, Int32(1))
        
        
        case .backlog:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrencePlacement_lift(_ buf: RustBuffer) throws -> RecurrencePlacement {
    return try FfiConverterTypeRecurrencePlacement.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecurrencePlacement_lower(_ value: RecurrencePlacement) -> RustBuffer {
    return FfiConverterTypeRecurrencePlacement.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A day of the week (for the weekly `BYDAY` picker). Mirrors [`cal_core::Weekday`].
 */

public enum Weekday: Equatable, Hashable {
    
    case monday
    case tuesday
    case wednesday
    case thursday
    case friday
    case saturday
    case sunday





}

#if compiler(>=6)
extension Weekday: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWeekday: FfiConverterRustBuffer {
    typealias SwiftType = Weekday

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Weekday {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .monday
        
        case 2: return .tuesday
        
        case 3: return .wednesday
        
        case 4: return .thursday
        
        case 5: return .friday
        
        case 6: return .saturday
        
        case 7: return .sunday
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Weekday, into buf: inout [UInt8]) {
        switch value {
        
        
        case .monday:
            writeInt(&buf, Int32(1))
        
        
        case .tuesday:
            writeInt(&buf, Int32(2))
        
        
        case .wednesday:
            writeInt(&buf, Int32(3))
        
        
        case .thursday:
            writeInt(&buf, Int32(4))
        
        
        case .friday:
            writeInt(&buf, Int32(5))
        
        
        case .saturday:
            writeInt(&buf, Int32(6))
        
        
        case .sunday:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWeekday_lift(_ buf: RustBuffer) throws -> Weekday {
    return try FfiConverterTypeWeekday.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWeekday_lower(_ value: Weekday) -> RustBuffer {
    return FfiConverterTypeWeekday.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTaskRecurrence: FfiConverterRustBuffer {
    typealias SwiftType = TaskRecurrence?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTaskRecurrence.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTaskRecurrence.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRecurrenceEnd: FfiConverterRustBuffer {
    typealias SwiftType = RecurrenceEnd?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRecurrenceEnd.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRecurrenceEnd.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeMonthDay: FfiConverterRustBuffer {
    typealias SwiftType = [MonthDay]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeMonthDay.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeMonthDay.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeWeekday: FfiConverterRustBuffer {
    typealias SwiftType = [Weekday]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeWeekday.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeWeekday.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMonthDay: FfiConverterRustBuffer {
    typealias SwiftType = [MonthDay]

    public static func write(_ value: [MonthDay], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMonthDay.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MonthDay] {
        let len: Int32 = try readInt(&buf)
        var seq = [MonthDay]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMonthDay.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWeekday: FfiConverterRustBuffer {
    typealias SwiftType = [Weekday]

    public static func write(_ value: [Weekday], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWeekday.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Weekday] {
        let len: Int32 = try readInt(&buf)
        var seq = [Weekday]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWeekday.read(from: &buf))
        }
        return seq
    }
}
/**
 * Parse a calendar attendee entry into its display name and email.
 *
 * Accepts `"Display Name <email@host>"` or a bare `"email@host"`, delegating
 * the split to [`cal_core::attendee::parse`] so the mobile UI and every
 * desktop adapter share one parser.
 */
public func parseAttendee(entry: String) -> ParsedAttendee  {
    return try!  FfiConverterTypeParsedAttendee_lift(try! rustCall() {
    uniffi_cal_ffi_fn_func_parse_attendee(
        FfiConverterString.lower(entry),$0
    )
})
}
/**
 * Parse an RFC 5545 `RRULE` value into a [`TaskRecurrence`]. Tolerates a
 * leading `RRULE:` and surrounding whitespace; returns `None` when there is no
 * usable `FREQ`. Unmodelled parts are ignored.
 */
public func rruleToTaskRecurrence(rrule: String) -> TaskRecurrence?  {
    return try!  FfiConverterOptionTypeTaskRecurrence.lift(try! rustCall() {
    uniffi_cal_ffi_fn_func_rrule_to_task_recurrence(
        FfiConverterString.lower(rrule),$0
    )
})
}
/**
 * Serialize a [`TaskRecurrence`] into an RFC 5545 `RRULE` value (without the
 * `RRULE:` prefix), e.g. `FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE`.
 *
 * Errors only if an `OnDate` end carries an unparseable date string.
 */
public func taskRecurrenceToRrule(recurrence: TaskRecurrence)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRecurrenceError_lift) {
    uniffi_cal_ffi_fn_func_task_recurrence_to_rrule(
        FfiConverterTypeTaskRecurrence_lower(recurrence),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cal_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_cal_ffi_checksum_func_parse_attendee() != 55709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cal_ffi_checksum_func_rrule_to_task_recurrence() != 23397) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cal_ffi_checksum_func_task_recurrence_to_rrule() != 25991) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCalFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all