// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The question [`apply_signature`] answers, over the wire.
 */
export type ApplySignatureInput = { description: string, body: string, };
