// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentCapabilities } from "./AssignmentCapabilities";

/**
 * The question [`task_assignment_mode`] answers, over the wire.
 */
export type AssignmentModeInput = { 
/**
 * The list's capabilities, or none when the list has none or is unknown.
 */
capabilities: AssignmentCapabilities | null, };
