// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two calendar weeks the backlog rail splits its deadlines into, as
 * inclusive day bounds.
 */
export type BacklogWeeks = { 
/**
 * First day of the week `today` falls in.
 */
thisWeekStart: string, 
/**
 * Last day of that week, inclusive.
 */
thisWeekEnd: string, nextWeekStart: string, 
/**
 * Last day of the following week, inclusive.
 */
nextWeekEnd: string, };
