// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fields a change is carried in.
 */
export type CarryableFields = { title: string, start: string, end: string, all_day: boolean, location: string | null, description: string | null, };
