// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a list does at day start with a task whose plan lapsed.
 */
export type CarryOverDefault = "ask" | "today" | "backlog";
