// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One member of the group, as the caller knows it.
 */
export type CarryTarget = { calendar_id: string, event_id: string, 
/**
 * The name to show when reporting what happened to it.
 */
title: string, 
/**
 * Whether Aperio may write to the calendar it lives in.
 */
writable: boolean, };
