// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarryField } from "./CarryField";
import type { CarryTarget } from "./CarryTarget";

/**
 * What carrying would do, decided before anything is written.
 */
export type CarryPlan = { 
/**
 * The fields that actually differ from the saved event.
 */
changed: Array<CarryField>, 
/**
 * Members Aperio can and will write.
 */
targets: Array<CarryTarget>, 
/**
 * Members it must leave alone, and the user has to be told about.
 */
skipped: Array<CarryTarget>, 
/**
 * Whether the plan is worth asking the user about at all.
 *
 * Part of the plan rather than a separate call: it is two comparisons, and
 * crossing a door for them would be silly — but writing them out on the
 * other side would be a twin, which is the thing this whole move is
 * against.
 */
worth_carrying: boolean, };
