// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the fields that travel.
 */
export type CarryField = "title" | "start" | "end" | "all_day" | "location" | "description";
