// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * What the planners read of a task — by the same field names as `Task`, so a
 * full task's JSON deserializes into it. `scheduled_date` stays text: only
 * its presence matters here, and the core never compares it.
 */
export type CascadeTask = { id: string, status: TaskStatus, parent_id: string | null, scheduled_date: string | null, };
