// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorLabelId } from "./ColorLabelId";

/**
 * Full color-label record (section 8).
 *
 * Labels exist app-wide: any event or task can reference one through
 * its `color_label` field. The label's `hex` overrides the container's
 * color when rendering — see `DESIGN.md` section 8.2 for the priority
 * rules.
 */
export type ColorLabel = { id: ColorLabelId, name: string, 
/**
 * Hex color value including the leading `#`, e.g. `#e53935`.
 */
hex: string, 
/**
 * `true` for an *ad-hoc* one-off color created via the custom-color
 * picker (its `name` is just the hex). Ad-hoc labels are hidden from
 * the palette-management UI and deduplicated by hex, but otherwise
 * resolve exactly like a named label. `#[serde(default)]` keeps older
 * sync payloads (which lack the field) deserialising to a named label.
 */
ad_hoc: boolean, };
