// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `label: value` line, with the label exactly as the invitation wrote it.
 *
 * A named pair rather than a tuple. Tuples are fine inside Rust and awkward
 * everywhere else: they serialise as bare arrays, so a reader has to know that
 * the first slot is the label, and UniFFI records cannot carry them at all.
 * The frontends' own `ConferenceDetail` is this shape already.
 */
export type ConferenceDetail = { 
/**
 * The sender's word, verbatim — this is DATA, not a key to look up.
 */
label: string, value: string, };
