// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The account's own user id in one list, or none. A list the question does
 * not name has no identity, and a task in it is offered whoever holds it.
 */
export type DayStartIdentity = { list_id: string, me: string | null, };
