// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The set a position counts within, for rules written with `BYSETPOS`.
 */
export type DaySet = "weekday" | "weekend_day";
