// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A task's dates after "move to today": the deadline is today, and the plan
 * is today only when it had lapsed — absent, the plan stays as it was.
 */
export type DayStartMoved = { deadline_date: string, scheduled_date?: string, };
