// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";
import type { TaskUser } from "./TaskUser";

/**
 * What the day rule reads of a task — by the same field names as `Task`, so
 * a full task's JSON deserializes into it, plus the one thing only the caller
 * can know.
 */
export type DayTask = { id: string, list_id: string, title: string, status: TaskStatus, priority: TaskPriority, scheduled_date: string | null, scheduled_time: string | null, scheduled_end_time: string | null, deadline_date: string | null, deadline_time: string | null, parent_id: string | null, assignees: Array<TaskUser>, 
/**
 * The LOCAL day the task was completed on, or `None` when it carries no
 * completion instant. Resolved by the caller from `completed_at` with the
 * zone the caller knows; the core reads none. A finished task with no
 * planned day belongs to this day.
 */
completed_day: string | null, };
