// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the calendar's day and week views lay out events.
 */
export type DayViewMode = "grid" | "list";
