// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The visible day window as it is stored.
 */
export type DayWindowMinutes = { start_min: number, end_min: number, };
