// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklogWeeks } from "./BacklogWeeks";

/**
 * The question [`split_deadlines_by_week`] answers, over the wire.
 */
export type DeadlineSplitInput = { 
/**
 * The deadline of each item, in the caller's order; `null` for an item
 * without one.
 */
deadlines: Array<string | null>, weeks: BacklogWeeks, };
