// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventGroupMember } from "./EventGroupMember";

/**
 * A set of events that mean one appointment.
 */
export type EventGroup = { id: string, created_at: string, updated_at: string, 
/**
 * The whole membership, always. A group is small and only meaningful
 * entire, so it travels and is stored as one value rather than as a
 * stream of additions and removals that could interleave.
 */
members: Array<EventGroupMember>, };
