// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The minimum a row has to carry to be foldable.
 */
export type FoldableEvent = { calendar_id: string, 
/**
 * The id membership is keyed by — the series master, resolved by the
 * caller, because only a rendered row knows which series it belongs to.
 */
series_id: string, start: string | null, all_day: boolean, 
/**
 * Whether the user can ACT on this row — see [`actionable`].
 *
 * Absent means "the core decides", which is the answer every caller
 * wants: the only rows Aperio has that cannot be acted on are the
 * read-only videoconference copies, and the core recognises those. It is
 * an option rather than a plain bool so a caller that knows more — which
 * calendars are read-only, say — can still say so without the rule having
 * to guess.
 */
actionable: boolean | null, };
