// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of header a synthetic row is.
 */
export type GroupKind = "backlog" | "list" | "section" | "done" | "deferred" | "overdue" | "today" | "cancelled";
