// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupKind } from "./GroupKind";

/**
 * What it takes to word a header — and to find it again.
 */
export type GroupHead = { kind: GroupKind, 
/**
 * The enclosing header's id; `None` at the top level. What a synthetic
 * row's `parent_id` is on the caller's side.
 */
parentId: string | null, 
/**
 * The owning list, for list and section headers.
 */
listId?: string, 
/**
 * The section row, for section headers.
 */
sectionId?: string, 
/**
 * Tasks under this header. The whole subtree for the active groups; the
 * top-level items only for the terminal ones (Erledigt, Abgebrochen).
 */
count: number, 
/**
 * Present only when Erledigt splits: done tasks that are mine or nobody's.
 */
mine?: number, 
/**
 * Present only when Erledigt splits: done tasks assigned to someone else.
 */
others?: number, };
