// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupableTask } from "./GroupableTask";
import type { PriorityScale } from "./PriorityScale";
import type { Section } from "./Section";
import type { TaskGroupBy } from "./TaskGroupBy";
import type { TaskUser } from "./TaskUser";

/**
 * Everything the rule needs, and nothing it does not.
 */
export type GroupingInput = { tasks: Array<GroupableTask>, 
/**
 * List id → display name. A list absent here is named — and ordered —
 * by its id.
 */
lists: { [key in string]: string }, 
/**
 * List id → its sections, as the store holds them. Order irrelevant:
 * sections are sorted by name here.
 */
sections: { [key in string]: Array<Section> }, 
/**
 * The day the deferred gate and the time groups compare against. A
 * parameter, never the clock (see `tests/core_contracts.rs`).
 */
today: string, 
/**
 * List id → the connected user, for the Erledigt mine/others split.
 * Absent or `null` means a personal list: everything counts as mine.
 */
currentUserByList: { [key in string]: TaskUser | null }, groupBy: TaskGroupBy, 
/**
 * The user's priority system — decides how many bands the sibling
 * ordering has.
 */
scale: PriorityScale, 
/**
 * Ids whose children are hidden: task ids and synthetic header ids alike.
 */
collapsed: Array<string>, 
/**
 * The app's language tag, for the collation of titles and names. Empty
 * answers the default, like every unknown tag.
 */
language: string, };
