// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneRegion } from "./ZoneRegion";

/**
 * A listed zone, named in parts. Its position in [`listed_zone_labels`] is
 * its position in [`crate::listed_zones`].
 */
export type ListedZone = { 
/**
 * The tzdata id, `America/Indiana/Indianapolis`.
 */
zone: string, 
/**
 * The last part with `_` read as a space, `Indianapolis`.
 */
city: string, 
/**
 * The middle part of a three-part id, `Indiana`; `null` otherwise.
 */
area: string | null, region: ZoneRegion, };
