// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZoneOffset } from "./ZoneOffset";

/**
 * A listed zone's offsets.
 */
export type ListedOffset = { 
/**
 * At the instant asked for: the offset the entry shows.
 */
offset: ZoneOffset, 
/**
 * Its standard time as of today: the smallest offset in the year from
 * today (decision 29a). The list is ordered by it.
 */
standard: ZoneOffset, };
