// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which part of an entry a word matched.
 */
export type MatchField = "city" | "area" | "region" | "zone_id" | "alias" | "offset";
