// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The least a row needs for the duplicate filter.
 */
export type MeetingFilterEvent = { calendar_id: string, location: string | null, description: string | null, 
/**
 * Whether this row is already a member of a group.
 *
 * A grouped meeting row must NOT be dropped: the folding is what hides it
 * then, and it hides it while COUNTING it — the row says "2×" and the
 * group can be opened. Dropped first, the count would be a lie about a
 * row that is not there.
 *
 * This is also the transition. As automatic grouping spreads, the filter
 * quietly stops applying to the pairs it covers, and what is left is the
 * case it was written for: a meeting whose partner is not in view.
 */
grouped: boolean, };
