// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A meeting row and the appointment it belongs to, as positions in the input.
 */
export type MeetingLinkPair = { 
/**
 * The row from the meetings calendar.
 */
meeting: number, 
/**
 * The ordinary calendar entry for the same meeting.
 */
event: number, 
/**
 * The join URL both carry — the identity this rests on.
 */
join_url: string, };
