// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission level on a task-list share (Vikunja `0/1/2`). Adapters
 * without per-share roles (Todoist) report `None` on the share.
 * See DESIGN §9.7 "Mitglieder-/Freigabe-Verwaltung".
 */
export type MemberRight = "read" | "write" | "admin";
