// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the move can be: the day to write, and whether it is the series
 * advanced by one step rather than the day that was asked for.
 */
export type MoveTarget = { date: string | null, advanced: boolean, };
