// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OccurrenceTask } from "./OccurrenceTask";

/**
 * The question [`expand_task_occurrences`] answers, over the wire.
 */
export type OccurrenceInput = { tasks: Array<OccurrenceTask>, 
/**
 * The window, both ends inclusive.
 */
from: string, to: string, 
/**
 * Cap on the rendered occurrences of one task; absent = 400.
 */
max_per_task: number | null, };
