// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaySet } from "./DaySet";
import type { Weekday } from "./Weekday";

/**
 * One part of the sentence: a key the surfaces look up, and the values it
 * takes. The renderer puts no rule of its own on top — it looks up names and
 * joins lists.
 */
export type Phrase = { 
/**
 * The full i18n key, for example `recurrenceSummary.every.week`.
 */
key: string, 
/**
 * i18next's `count`, which also picks the plural form.
 */
count?: number, 
/**
 * Days of the week, Monday first whatever order the rule listed them.
 */
weekdays?: Array<Weekday>, 
/**
 * One day of the week.
 */
weekday?: Weekday, 
/**
 * A position in the month or year: 1 to 5, or -1 for the last.
 */
ordinal?: number, 
/**
 * Days of the month, in order.
 */
month_days?: Array<number>, 
/**
 * A month, 1 to 12.
 */
month?: number, 
/**
 * A day, `YYYY-MM-DD`, for the end of a bounded rule.
 */
date?: string, 
/**
 * A set of days a position counts within.
 */
set?: DaySet, };
