// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriorityKeys } from "./PriorityKeys";

/**
 * The priority keys per scale.
 */
export type PriorityKeysByScale = { three: PriorityKeys, two: PriorityKeys, };
