// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The keys for every priority under one scale; `None` where nothing is
 * announced.
 */
export type PriorityKeys = { low: string | null, medium: string | null, high: string | null, };
