// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * What the progress reads of a task — by the same field names as `Task`, so
 * a full task's JSON deserializes into it.
 */
export type ProgressTask = { id: string, status: TaskStatus, parent_id: string | null, };
