// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DESIGN §9.12: anchor for a recurring task's next occurrence.
 */
export type RecurrenceAnchor = "from_date" | "from_completion";
