// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DESIGN §9.12: where a recurring task's next instance is placed.
 */
export type RecurrencePlacement = "schedule" | "backlog";
