// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the sentence needs.
 */
export type RecurrenceSummaryQuestion = { 
/**
 * The rule, with or without the `RRULE:` prefix. Empty: no repeat.
 */
rrule: string, 
/**
 * The day the series starts, `YYYY-MM-DD` on the series' own clock. A
 * rule leaves out what its start already says ("every month" repeats on
 * the start's day of the month).
 */
start: string, 
/**
 * The day the last occurrence of a bounded rule falls on, same clock,
 * when the shell worked it out. `UNTIL` is written three ways by three
 * providers, and it is a bound, not an occurrence: only the expander the
 * views already use can say which day the series really ends on
 * (decision 85a). Without it the sentence says "with an end date".
 */
last_day: string | null, };
