// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderKind = { "type": "relative", minutes_before: number, } | { "type": "absolute", at: string, } | { "type": "app_start" } | { "type": "email", minutes_before: number, };
