// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unit a rule repeats in, for a rule that cannot be put into words but
 * whose `FREQ` was read.
 */
export type RepeatUnit = "second" | "minute" | "hour" | "day" | "week" | "month" | "year";
