// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorLabelId } from "./ColorLabelId";

/**
 * A sub-grouping of tasks *within* a single task list — a Vikunja
 * bucket or a Todoist section. Distinct from a nested project
 * (`TaskList.parent_id`): sections never contain other sections and
 * never contain sub-lists, they only group the tasks of one list.
 *
 * Backends without the concept (Google Tasks, CalDAV VTODO, EWS,
 * local) simply return no sections from `TasksFeature::list_sections`
 * and leave every task's `section_id` at `None`.
 */
export type Section = { id: string, 
/**
 * The `TaskList.id` this section belongs to.
 */
list_id: string, name: string, 
/**
 * Optional binding to a global color label — see `Calendar.color_label`.
 * Cascades to the section's tasks that carry no color of their own
 * (resolution chain: task → section → list). A label *reference*
 * (not a frozen hex) so recoloring the label recolors every bound
 * section live. A purely local, Aperio-synced concept like the
 * section itself — no provider round-trip.
 */
color_label: ColorLabelId | null, 
/**
 * Display order within the list; lower sorts first. Mirrors the
 * `position` Vikunja attaches to buckets and the order Todoist
 * gives its sections.
 */
order: number, };
