// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * The question [`self_assign_on_status_change`] answers, over the wire. A
 * user is its id.
 */
export type SelfAssignInput = { 
/**
 * The status the task changes to.
 */
status: TaskStatus, 
/**
 * The assignee ids as the task carries them, in order.
 */
assignees: Array<string>, 
/**
 * The account's own id, or none when the adapter reports no identity.
 */
me: string | null, 
/**
 * The Settings → Tasks toggle.
 */
enabled: boolean, };
