// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShiftRefusal } from "./ShiftRefusal";

/**
 * What shifting a series by whole days writes.
 */
export type SeriesShift = { "outcome": "shifted", rrule: string, } | { "outcome": "refused", reason: ShiftRefusal, };
