// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * One write the caller applies: `task_id` becomes `status`; when
 * `scheduled_date` is set, the task's scheduled day becomes it too — the
 * "started → pin to today" companion.
 */
export type StatusWrite = { task_id: string, status: TaskStatus, scheduled_date?: string, };
