// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressTask } from "./ProgressTask";

/**
 * The question [`subtask_progress`] answers, over the wire.
 */
export type SubtaskProgressInput = { tasks: Array<ProgressTask>, };
