// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pair the user has said is not one appointment.
 *
 * Stored and compared in a CANONICAL order — the smaller `(calendar, event)`
 * first as text — so "A and B" and "B and A" are one decision. Without that
 * the same pair could be declined from one side and offered again from the
 * other.
 */
export type SuggestionDecline = { calendar_a: string, event_a: string, calendar_b: string, event_b: string, declined_at: string, 
/**
 * When the pair was last grouped BY HAND, if ever.
 *
 * A refusal that cannot lose is a trap: automatic grouping consults these
 * marks, so one arriving from a device that was offline for three weeks
 * would tear apart a group made deliberately yesterday. Grouping two
 * events by hand is the opposite statement, and it stamps this.
 *
 * The pair counts as refused iff `declined_at` is the later of the two.
 * Neither ever moves backwards, so two devices still merge by taking the
 * later of each and the answer does not depend on arrival order — the
 * union rule migration 0037 relies on, kept intact.
 */
cleared_at?: string | null, };
