// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarryOverDefault } from "./CarryOverDefault";

/**
 * One list's override: any subset of the three per-list settings.
 */
export type TaskListOverride = { cascade?: boolean, auto_date?: boolean, carry_over_default?: CarryOverDefault, };
