// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskListGlobals } from "./TaskListGlobals";
import type { TaskListOverride } from "./TaskListOverride";
import type { TaskListOverrideEntry } from "./TaskListOverrideEntry";
import type { TaskSettingsStored } from "./TaskSettingsStored";

/**
 * One question to the task-settings rules.
 */
export type TaskSettingsQuestion = { "rule": "read", stored: TaskSettingsStored, } | { "rule": "effective", globals: TaskListGlobals, 
/**
 * The list's own override, if it has one.
 */
list_override: TaskListOverride | null, } | { "rule": "countdown_days_to_store", value: number | null, } | { "rule": "day_window_to_store", start_min: number | null, end_min: number | null, } | { "rule": "with_list_override", list_overrides: Array<TaskListOverrideEntry>, list_id: string, list_override: TaskListOverride, };
