// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRight } from "./MemberRight";
import type { TaskUser } from "./TaskUser";

/**
 * One membership/share row of a task list: who has access, at what
 * right (if the backend models roles), and whether the invitation is
 * still pending acceptance (Todoist email invites are `pending` until
 * accepted). Distinct from `TaskUser` in the assignee pool — this is
 * the *editable* share list, not the effective members.
 */
export type TaskListShare = { user: TaskUser, right: MemberRight | null, pending: boolean, };
