// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarryOverDefault } from "./CarryOverDefault";
import type { CheckoffMode } from "./CheckoffMode";
import type { DayViewMode } from "./DayViewMode";
import type { TaskListOverrideEntry } from "./TaskListOverrideEntry";

/**
 * The settings, read.
 */
export type TaskSettingsRead = { cascade_enabled: boolean, auto_date: boolean, auto_self_assign: boolean, visual_effort_sizing: boolean, two_level_priority: boolean, remind_untimed_today: boolean, remind_deadline_arrived: boolean, remind_deadline_countdown: boolean, 
/**
 * 1..=30.
 */
deadline_countdown_days: number, day_view_mode: DayViewMode, 
/**
 * Minutes from midnight, on the half hour.
 */
day_start_min: number, 
/**
 * Minutes from midnight, on the half hour, after the start.
 */
day_end_min: number, checkoff_mode: CheckoffMode, carry_over_default: CarryOverDefault, 
/**
 * One of [`DAY_START_TRIGGERS`].
 */
day_start_trigger: string, 
/**
 * In the key order a JavaScript object gives them.
 */
list_overrides: Array<TaskListOverrideEntry>, };
