// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarryOverDefault } from "./CarryOverDefault";

/**
 * The three global settings a list override can override.
 */
export type TaskListGlobals = { cascade_enabled: boolean, auto_date: boolean, carry_over_default: CarryOverDefault, };
