// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskListOverride } from "./TaskListOverride";

/**
 * A list's override, with the list it belongs to.
 */
export type TaskListOverrideEntry = { list_id: string, settings: TaskListOverride, };
