// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stored strings, one per preference; `None` when not stored — or when
 * reading it failed.
 */
export type TaskSettingsStored = { 
/**
 * `tasks.cascadeStatusCoupling`
 */
cascade: string | null, 
/**
 * `tasks.autoDateOnStart`
 */
auto_date: string | null, 
/**
 * `tasks.autoSelfAssign`
 */
auto_self_assign: string | null, 
/**
 * `tasks.visualEffortSizing`
 */
visual_effort_sizing: string | null, 
/**
 * `tasks.twoLevelPriority`
 */
two_level_priority: string | null, 
/**
 * `tasks.remindUntimedToday`
 */
remind_untimed_today: string | null, 
/**
 * `tasks.remindDeadlineArrived`
 */
remind_deadline_arrived: string | null, 
/**
 * `tasks.remindDeadlineCountdown`
 */
remind_deadline_countdown: string | null, 
/**
 * `tasks.deadlineCountdownDays`
 */
deadline_countdown_days: string | null, 
/**
 * `calendar.dayViewMode`
 */
day_view_mode: string | null, 
/**
 * `calendar.dayStartMin`
 */
day_start_min: string | null, 
/**
 * `calendar.dayEndMin`
 */
day_end_min: string | null, 
/**
 * `tasks.checkoffMode`
 */
checkoff_mode: string | null, 
/**
 * `tasks.carryOverDefault`
 */
carry_over_default: string | null, 
/**
 * `tasks.dayStartTrigger`
 */
day_start_trigger: string | null, 
/**
 * `tasks.listOverrides`, a JSON object keyed by list id.
 */
list_overrides: string | null, };
