// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aperio-only effort estimate, modelled exactly like `TaskPriority` (three
 * levels). `Default` is `Medium` — the neutral middle — so `#[serde(default)]`
 * fields and task JSON synced before this field existed resolve to it.
 */
export type TaskEffort = "small" | "medium" | "large";
