// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarryOverDefault } from "./CarryOverDefault";

/**
 * A list's settings in effect.
 */
export type TaskListEffective = { cascade: boolean, auto_date: boolean, carry_over_default: CarryOverDefault, };
