// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user in the task domain — used as a task assignee, as a member of a
 * task list's collaborator pool, and as the connected account's own
 * identity ("me"). `id` is the provider-native user id (Vikunja numeric
 * id stringified, Todoist user id, …); `name` is a display label;
 * `email` is best-effort (some providers omit it from the user listing).
 * See DESIGN §9.7 "Aufgaben-Zuweisung an andere Nutzer".
 */
export type TaskUser = { id: string, name: string, email: string | null, };
