// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorLabelId } from "./ColorLabelId";
import type { ContainerColor } from "./ContainerColor";
import type { SoundConfig } from "./SoundConfig";

export type TaskList = { id: string, name: string, color: ContainerColor | null, 
/**
 * Optional binding to a global color label — see `Calendar.color_label`.
 */
color_label: ColorLabelId | null, default_sound: SoundConfig | null, 
/**
 * For task-capable calendars (CalDAV/VTODO, local): the calendar ID.
 * For standalone task lists: `None`.
 */
embedded_in_calendar: string | null, 
/**
 * Parent project id for backends with nested projects (Vikunja,
 * Todoist). `None` ⇒ a top-level list, or a flat backend with no
 * nesting at all (Google Tasks, CalDAV-per-calendar, …). The id
 * refers to another `TaskList.id` from the same adapter.
 *
 * `#[serde(default)]` so wire payloads written before nested
 * projects existed deserialise into a flat (parentless) list.
 */
parent_id: string | null, read_only: boolean, };
