// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a rule was not put into words. Each one names a shape, so the surfaces
 * can say what kind of rule it is and a later version can word more of them.
 */
export type UndescribedReason = "unreadable" | "unknown_part" | "set_position" | "ordinal" | "several_positions" | "limited_months" | "mixed_month_days" | "no_occurrences" | "week_start" | "count_and_until";
