// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the list: the UTC entry, or a listed zone by its position.
 */
export type ZoneRef = { "kind": "utc" } | { "kind": "zone", position: number, };
