// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegionName } from "./RegionName";
import type { ZoneOffsets } from "./ZoneOffsets";

/**
 * A search over the list.
 */
export type ZoneSearchQuestion = { 
/**
 * What the person typed. Words separated by spaces must all match.
 */
query: string, 
/**
 * Every region's name in the surface's language; all nine are required.
 */
region_names: Array<RegionName>, 
/**
 * The offsets the list shows, from [`zone_offsets`]. With them hits come in
 * the list's order; without them no word matches an offset, and hits come
 * with the UTC entry first and then by position.
 */
offsets: ZoneOffsets | null, };
