// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The question [`zone_choice`] answers.
 */
export type ZoneChoiceQuestion = { 
/**
 * The zone the series stores, as it stores it.
 */
stored: string | null, 
/**
 * The zone name the device reports, as it reports it.
 */
device: string | null, };
