// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a zone name relates to the list.
 */
export type ZoneChoice = { "kind": "utc" } | { "kind": "listed", position: number, } | { "kind": "not_listed", name: string, canonical: string, } | { "kind": "unreadable", name: string, };
