// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The part of the world a listed zone's id starts with.
 */
export type ZoneRegion = "africa" | "america" | "antarctica" | "asia" | "atlantic" | "australia" | "europe" | "indian" | "pacific";
